name: deploy-main-to-gcp.yml

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/rotary-phone
          chmod 600 ~/.ssh/rotary-phone
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts        
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy over SSH
        shell: bash
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          APP_DIR: /home/jacec/bug-free-rotary-phone-devops
          PM2_NAME: ${{ vars.PM2_NAME }}
        run: |
          ssh -i ~/.ssh/rotary-phone -T "jacec@$SSH_HOST" << EOF
            set -e

            echo "WHOAMI:"
            whoami

            echo "HOME DIR:"
            echo $HOME

            echo "APP_DIR VALUE:"
            echo "$APP_DIR"

            echo "PWD BEFORE CD:"
            pwd

            echo "TRYING TO CD INTO APP_DIR:"
            cd "$APP_DIR" || { echo "FAILED TO CD INTO $APP_DIR"; exit 1;}      

            echo "PWD AFTER CD:"
            pwd

            echo "LISTING DIRECTORY CONTENTS:"
            ls -la

            git pull
            npm ci

            pm2 delete "$PM2_NAME" || true
            pm2 start -f app.mjs --name "$PM2_NAME"
            pm2 save
          EOF
